// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh9lQl8UxAe9eiUbNVo8OPS1TDss4BHgg',
    appId: '1:14847561210:web:219d5e31a4ffa5f1e82843',
    messagingSenderId: '14847561210',
    projectId: 'reddit-clone-596ee',
    authDomain: 'reddit-clone-596ee.firebaseapp.com',
    storageBucket: 'reddit-clone-596ee.appspot.com',
    measurementId: 'G-RT5QCG8LE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjCdCZFaZ8tn3Fmy603yfqbRnPJzElAxs',
    appId: '1:14847561210:android:29aeaf37db1bf7aee82843',
    messagingSenderId: '14847561210',
    projectId: 'reddit-clone-596ee',
    storageBucket: 'reddit-clone-596ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGi8uipe30KuTpdrq-oaYIhYfDGPclXgo',
    appId: '1:14847561210:ios:7ff3003a6178bcade82843',
    messagingSenderId: '14847561210',
    projectId: 'reddit-clone-596ee',
    storageBucket: 'reddit-clone-596ee.appspot.com',
    iosClientId: '14847561210-d742592qu5t8h14kntoe2nokuuf185ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGi8uipe30KuTpdrq-oaYIhYfDGPclXgo',
    appId: '1:14847561210:ios:7ff3003a6178bcade82843',
    messagingSenderId: '14847561210',
    projectId: 'reddit-clone-596ee',
    storageBucket: 'reddit-clone-596ee.appspot.com',
    iosClientId: '14847561210-d742592qu5t8h14kntoe2nokuuf185ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
